//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupancy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MST_CATEGORIES
    {
        public string CATEGORY_ID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public string CATEGORY_DETAILS { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    }
}
