//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupancy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MST_BRANCH
    {
        public string BRANCH_ID { get; set; }
        public string BRANCH_NAME { get; set; }
        public string ISACTIVE { get; set; }
    }
}
