//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupancy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_em_employeedetails
    {
        public int ID { get; set; }
        public string EmployeeCode { get; set; }
        public string FullName { get; set; }
        public string isactive { get; set; }
        public string companycode { get; set; }
        public string companyname { get; set; }
        public string branchname { get; set; }
        public Nullable<int> branchid { get; set; }
        public Nullable<int> REPTMGR1 { get; set; }
        public string REPORTINGMANAGER1CODE { get; set; }
        public string STATE { get; set; }
        public string Mobile { get; set; }
        public string OFFICEEMAIL { get; set; }
        public Nullable<int> ROLEID { get; set; }
    }
}
