//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occupancy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComplianceEntities4 : DbContext
    {
        public ComplianceEntities4()
            : base("name=ComplianceEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_em_employeedetails> tbl_em_employeedetails { get; set; }
        public DbSet<TBL_MST_BRANCH> TBL_MST_BRANCH { get; set; }
        public DbSet<TBL_MST_CATEGORIES> TBL_MST_CATEGORIES { get; set; }
        public DbSet<TBL_MST_DOCUMENT_TYPES> TBL_MST_DOCUMENT_TYPES { get; set; }
        public DbSet<TBL_MST_ROLES> TBL_MST_ROLES { get; set; }
    }
}
